name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8'     

    - name: Restore
      run: dotnet restore RamTrac.sln
    
    - name: Build with dotnet
      run: dotnet build --no-restore
    
