name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8'     
    - name: Setup NuGet Sources
      run: dotnet nuget add source https://nuget.pkg.github.com/csu-chhs/index.json --name "GitHub" --store-password-in-clear-text --username dstegelman --password "${{ secrets.DEREK_TOKEN }}"

    - name: Restore
      run: dotnet restore RamTrac.sln
    
    - name: Build with dotnet
      run: dotnet build --no-restore
    
